# Introdução à Ciência de Dados - UFPB
Professor: Yuri Malheiros

## NumPy

Implemente a função `distance` abaixo. Ela deve receber dois pontos e retornar a distância euclidiana entre eles. Cada ponto é representado por um array do NumPy, por exemplo, `p1 = np.array([2,4])` representa o ponto com coordenadas `x=2` e `y=2`.

In [ ]:
import numpy as np

x, y  = input("digite o valor de x e y do primeiro ponto:" ).split()
k, w = input("digite o valor de x e y do segundo ponto:" ).split()
p1 = np.array((x, y), dtype = int)
p2 = np.array((k, w), dtype = int)
distancia = 0

def distance(p1, p2):
    """
    >>> distance(np.array([0,0]), np.array([1,1]))
    1.4142135623730951
    
    >>> distance(np.array([1,2]), np.array([3,4]))
    2.8284271247461903
    
    >>> distance(np.array([5,2]), np.array([-2,-1]))
    7.615773105863909
    """

    # ADICIONE O SEU CÓDIGO AQUI
    print ("A distancia entre os pontos é de: ", np.sqrt(np.sum((p1 - p2) ** 2)))

distance (p1, p2)


digite o valor de x e y do primeiro ponto:0 0
digite o valor de x e y do segundo ponto:1 1
A distancia entre os pontos é de:  1.4142135623730951


Implemente a função `n_distances` abaixo. Ela recebe um ponto (`p1`), como um array do NumPy, e uma lista de pontos (`points`), uma matriz do NumPy, onde cada linha representa um ponto.

Esta função deve retornar a distância de `p1` para todos os pontos da matriz `points`. O retorno também é uma matriz, onde cada linha tem a distância de `p1` para o ponto daquela linha.

In [19]:
import numpy as np

x, y = input("digite o valor de x e y do ponto 1:" ).split()
p1 = np.array((x, y), dtype = int)

linha = int(input("Digite o numero de linhas:"))
coluna = int(input("Digite o numero de colunas:"))

print("Digite os numeros para a matriz:: ")

m = list(map(int, input().split()))

points = np.array(m).reshape(linha, coluna)

def n_distances(p1, points):
    """
    >>> n_distances(np.array([0,0]), np.array([[1,1]]))
    array([1.41421356])
    
    >>> n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
    array([1.41421356, 2.82842712])
    
    >>> n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
    array([3.60555128, 1.41421356, 4.        , 9.05538514, 7.61577311])
    """
    
    # ADICIONE O SEU CÓDIGO AQUI
   
    print("Essa é a distancia entre o ponto 1 e os pontos na matiz: ", np.linalg.norm(p1 - points[:,None], axis=-1))

n_distances(p1, points)

digite o valor de x e y do ponto 1:0 0 
Digite o numero de linhas:2
Digite o numero de colunas:2
Digite os numeros para a matriz:: 
1 1 2 2
Essa é a distancia entre o ponto 1 e os pontos na matiz:  [[1.41421356]
 [2.82842712]]


## Teste

In [20]:
import doctest

doctest.testmod(verbose=True)


PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.7/doctest.py", line 1487, in run
    sys.settrace(save_trace)



Trying:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expecting:
    array([1.41421356])
**********************************************************************
File "__main__", line 18, in __main__.n_distances
Failed example:
    n_distances(np.array([0,0]), np.array([[1,1]]))
Expected:
    array([1.41421356])
Got:
    Essa é a distancia entre o ponto 1 e os pontos na matiz:  [[1.41421356]]
Trying:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expecting:
    array([1.41421356, 2.82842712])
**********************************************************************
File "__main__", line 21, in __main__.n_distances
Failed example:
    n_distances(np.array([0,0]), np.array([[1,1], [2,2]]))
Expected:
    array([1.41421356, 2.82842712])
Got:
    Essa é a distancia entre o ponto 1 e os pontos na matiz:  [[1.41421356]
     [2.82842712]]
Trying:
    n_distances(np.array([1,2]), np.array([[3,-1], [2,1], [5, 2], [10, 1], [-2, -5]]))
Expecting:
    array([3.60555128, 1.41421356, 4. 

TestResults(failed=3, attempted=3)